version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
    	- ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-root
      POSTGRES_DB: test-db
      POSTGRES_USER: root
    ports:
     - 5433:5422

  keycloak:
    build: 
      context: ./keycloak/
      dockerfile: ./keycloak/Dockerfile
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - "db"
