spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.56.4}:${DB_PORT:5433}/${DB_NAME:test-db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:postgres-root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.56.4:8088/realms/cs545/protocol/openid-connect/certs
debug: true
server:
  servlet:
    context-path: /api
