application:
  bucket:
    name: property-management-system

spring:
  application:
    name: pms
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/pmsdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        event:
          merge:
            entity_copy_observer: allow
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey:  AKIAWRRHHKBS3L4HXCJH
      secretKey: 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



